### PR TITLE
Update typescript to 4.3.5

### PR DESCRIPTION
**Pull request by DerKorb**
Updated typescript to 4.3.5 so it can be used with recent versions.

### CODE REVIEW

**Comment by phenomnomnominal** [comment]
Hmm, what happens if you use never versions currently? I don’t believe any TS APIs have changed, so I’d have expected any version above the listed version to work.

**Comment by DerKorb** [comment]
In my case the SyntaxKind enum needs to be extended for newer features. Also unfortunately typescript keeps changing the enums values. SyntaxKind.ClassDeclaration changed from 248 to 252 to 253 =(

**Comment by DerKorb** [comment]
Maybe I did something wrong and it should have automatically resolved to the newer version anyways.

**Comment by phenomnomnominal** [comment]
Hmm yeah, you've only actually updated the devDependencies, which won't change anything on an installed version. TypeScript should be being installed with this:

```
"peerDependencies": {
    "typescript": "^3 || ^4"
  },
```

Maybe you've got multiple copies of TS installed somehow, or it's resolving to an earlier version?

**Comment by DerKorb** [comment]
That must have been my problem yes, I have a bunch of repositories all doing some stuff with their own typescript versions. Thx for your feedback!

**Pull request closed without merging**
